### ISSUE TITLE
setMusicSpeed not working?

### ISSUE THREAD

**Issue by zyuzuguldu** [punker76/simple-music-player#35]
i want to change speed of music. used setMusicSpeed(5f) but not working.

i used like this.

// PlayerEngine.cs
this.sound.getLength(out lenms, FMOD.TIMEUNIT.MS).ERRCHECK();
this.sound.setMusicSpeed(5f).ERRCHECK();

**Comment by punker76** [comment]
@zyuzuguldu This function seems to work only for MOD/S3M/XM/IT/MID sequenced formats only.

https://stackoverflow.com/a/15439876/920384
