### ISSUE TITLE
How to close MahApps ProgressDialog without losing focus on child control?

### ISSUE THREAD

**Issue by dxdx347** [punker76/simple-music-player#41]
In my app, I'm loading a DocumentViewer for previewing and printing. Because loading can take up to a few seconds, I would like to display a ProgressDialog. The logic is this: display ProgressDialog, create and display DocumentViewer, close ProgressDialog. 

The problem is that when closing the dialog, the focus returns to the MainWindow, instead of remaining to the DocumentViewer window. I think it's because the dialog CloseAsync(). I've tried calling Focus(), Activate(), Show(), setting TopMost = true, setting the owner of the child window, but, although the window is displayed in front of the parent, the focus still returns to the parent. The only way to I restored the focus to the child was by doing a programmatic click inside the child window, in ProgressDialog.Closed event, but the disadvantage is that there is an ugly transition (child initially appears in front, then parent, then child again).

Can CloseAsync() be avoided? Or how to close MahApps ProgressDialog without losing focus on child control?

**Comment by punker76** [comment]
@dxdx347 It seems you choose the wrong repo ;-) Can you test this with the latest pre-release? This should fixed now (see also #2414)
