### ISSUE TITLE
Why SimpleMusicPlayer not use processor? "I like that"    :)

### ISSUE THREAD

**Issue by EAxp3** [punker76/simple-music-player#42]
I just want to know why,
there is a change or difference to other libraries as Naudio
:question: 
![captura1](https://cloud.githubusercontent.com/assets/15073580/15889945/e05b47d0-2d32-11e6-8a4a-0c563fbef565.PNG)
![captura](https://cloud.githubusercontent.com/assets/15073580/15889460/d7551762-2d30-11e6-82c8-32e7396e7020.PNG)

features of my system:
Windows 10 Pro x64
processor: AMD Athlon(tm) II X2 250 Processor 3.00 GHz
[Motherboard](https://pcel.com/PCChips-A51G-V7-1-73801)

--but on my laptop the opposite occurs --USE CPU :(

I hope you solve my question

I hope you continue with development.
It is an excellent program
use it daily to listen to music

Thank you :+1:

**Comment by punker76** [comment]
@EAxp3 Thanks!
- I planned some changes, flac support and some other ideas, maybe the music lib will be gone...
- The player uses the [FMOD](http://www.fmod.org/) library.
- How many CPU usage consumes the player on your Laptop?

**Comment by EAxp3** [comment]
version used: SimpleMP_v1.9.1_x64
Laptop: Windows 10 Home TH2 X64+AMD E1-1200 APU with Radeon(tm) HD Graphics 1.40 GHz + Audio Realtek
perhaps because of CPU or chip audio ??
It has low speed

CPU Usage: 
![consumo de cpu varia](https://cloud.githubusercontent.com/assets/15073580/15891148/e2b07bc6-2d38-11e6-9926-ea28bb78ece5.PNG)

change track:
![change pista](https://cloud.githubusercontent.com/assets/15073580/15891198/186ea026-2d39-11e6-8ec8-294f01bfab2c.png)

**Comment by punker76** [comment]
@EAxp3 I'll give you a 1.9.2 after my work tonight...

**Comment by Svetomech** [comment]
New version? Yay! Because the previous one wasn't really working properly to me.

**Comment by punker76** [comment]
@Svetomech @EAxp3 new version ready https://github.com/punker76/simple-music-player/releases/tag/v1.9.2

**Comment by Svetomech** [comment]
Thanks!
