### ISSUE TITLE
How to Run the project?

### ISSUE THREAD

**Issue by BrandedAlok** [punker76/simple-music-player#45]
When i am opening the file in Android studio it is displaying nothing to show?

![huhh55](https://cloud.githubusercontent.com/assets/21073030/18409525/d1502994-7766-11e6-8313-0aed73a3e518.jpg)

**Comment by Svetomech** [comment]
Why would you open a Visual Studio project in Android Studio? Their solution files are clearly incompatible, not to mention the programming languages used.

**Comment by punker76** [comment]
@BrandedAlok This player is not an Android project/app. It's written in C# and WPF/XAML and if you want to open the solution you need at minimum Visual Studio 2015 Community Edition.
