### ISSUE TITLE
cannot find the reqired file C:\Users\ssh\Documents\Visual Studio 2017\Projects\simple-music-player-dev\src\SimpleMusicPlayer.Tests\bin\Debug\SimpleMusicPlayer.Tests.dll file

### ISSUE THREAD

**Issue by great-ssh** [punker76/simple-music-player#50]
it gives this error when i want to make a setup of it with Advanced installer 12.8 : 
cannot find the reqired file C:\Users\ssh\Documents\Visual Studio 2017\Projects\simple-music-player-dev\src\SimpleMusicPlayer.Tests\bin\Debug\SimpleMusicPlayer.Tests.dll file

**Comment by punker76** [comment]
@great-ssh I really don't know how this installer works and how do you compiled SimpleMP...
